### ISSUE TITLE
Webcam stream stops in iOS

### ISSUE THREAD

**Issue by FrankX0** [jacksonliam/mjpg-streamer#206] opened 2019-05-02 16:23 UTC
When I access OctoPrint from my iPhone, the webcam stream (through MJPG-streamer) works as expected.
When I however switch to a different app and back, the stream does not update anymore. This happens when using both Chrome and Safari. Only after a forced refresh the stream works again, until the next switch.

This problem is actually caused by MJPG-Streamer: the demo page shows the same behaviour.
Does anyone know how to resolve this?

Additional information about my setup:
- Running on Raspberry Pi 3B+
- Pi Cam
- iOS 12.2
- MJPG-Streamer v0.1 (Oct 22, 2007)

**Comment by jacksonliam** [comment] 2019-05-02 19:28
I doubt it's caused by mjpg streamer. 

I'm pretty sure the browser/os will be closing the connection when you switch away from the browser. The stream works by http multipart, once the connection is closed you will need to reload it.

Try the JavaScript page on the demo site, perhaps iOS allows JS to continue when you reopen the browser.

**Closed by jacksonliam** 2019-05-02 19:28 UTC
