### ISSUE TITLE
Error:mmal: mmal_component_create_core: could not find component 'vc.ril.camera'

### ISSUE THREAD

**Issue by 13** [jacksonliam/mjpg-streamer#120] opened 2018-03-18 19:14 UTC
On Arch Linux ARM for Raspberry Pi 2 I get this error:

```
export LD_LIBRARY_PATH="/usr/lib"
mjpg_streamer -i "input_raspicam.so -d 0 -ex night -x 640 -y 480" -o "output_http.so -p 8080 -w /usr/www
MJPG Streamer Version: git rev: 8cc9d22c1e79905d529a248ccf05bbf0625e0bf3
Unknown DRC level: 0 i: fps.............: 5
 i: resolution........: 640 x 480
 i: camera parameters..............:

Sharpness 0, Contrast 0, Brightness 50
Saturation 0, ISO 0, Video Stabilisation No, Exposure compensation 0
Exposure Mode 'night', AWB Mode 'auto', Image Effect 'none'
Metering Mode 'average', Colour Effect Enabled No with U = 128, V = 128
Rotation 0, hflip No, vflip No
ROI x 0.000000, y 0.000000, w 1.000000 h 1.000000
 o: www-folder-path......: /usr/www/
 o: HTTP TCP port........: 8080
 o: HTTP Listen Address..: (null)
 o: username:password....: disabled
 o: commands.............: enabled
 i: Starting Camera
mmal: mmal_component_create_core: could not find component 'vc.ril.camera'
error create camera
```

```
ldd /usr/bin/mjpg_streamer 
        linux-vdso.so.1 (0x7ed19000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x76eba000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x76ea7000)
        libc.so.6 => /usr/lib/libc.so.6 (0x76d62000)
        /lib/ld-linux-armhf.so.3 => /usr/lib/ld-linux-armhf.so.3 (0x76efa000)
ldd /opt/vc/bin/raspistill 
        linux-vdso.so.1 (0x7ef48000)
        libmmal_core.so => /opt/vc/lib/libmmal_core.so (0x76f6a000)
        libmmal_util.so => /opt/vc/lib/libmmal_util.so (0x76f4a000)
        libmmal_vc_client.so => /opt/vc/lib/libmmal_vc_client.so (0x76f2f000)
        libbrcmGLESv2.so => /opt/vc/lib/libbrcmGLESv2.so (0x76f0a000)
        libbrcmEGL.so => /opt/vc/lib/libbrcmEGL.so (0x76ed1000)
        libm.so.6 => /usr/lib/libm.so.6 (0x76e4d000)
        libvcsm.so => /opt/vc/lib/libvcsm.so (0x76e38000)
        libbcm_host.so => /opt/vc/lib/libbcm_host.so (0x76e11000)
        libvchiq_arm.so => /opt/vc/lib/libvchiq_arm.so (0x76dfb000)
        libvcos.so => /opt/vc/lib/libvcos.so (0x76de1000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x76db7000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x76da2000)
        librt.so.1 => /usr/lib/librt.so.1 (0x76d8b000)
        libc.so.6 => /usr/lib/libc.so.6 (0x76c46000)
        /lib/ld-linux-armhf.so.3 => /usr/lib/ld-linux-armhf.so.3 (0x76f8a000)
ldd /usr/lib/mjpg-streamer/input_raspicam.so
        linux-vdso.so.1 (0x7edf5000)
        libmmal_core.so => /opt/vc/lib/libmmal_core.so (0x76eb7000)
        libmmal_util.so => /opt/vc/lib/libmmal_util.so (0x76e97000)
        libbcm_host.so => /opt/vc/lib/libbcm_host.so (0x76e70000)
        libc.so.6 => /usr/lib/libc.so.6 (0x76d2b000)
        /usr/lib/ld-linux-armhf.so.3 (0x76efc000)
        libvcos.so => /opt/vc/lib/libvcos.so (0x76d11000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x76ce7000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x76cd4000)
        librt.so.1 => /usr/lib/librt.so.1 (0x76cbd000)
        libvchiq_arm.so => /opt/vc/lib/libvchiq_arm.so (0x76ca7000)
```

**Comment by jacksonliam** [comment] 2018-03-19 08:27
Was going to close this as a duplicate of #117 as I don't have an Arch setup or time to create one to help fix this. 

But your post of ldd shows the linking is omitting lib mmal_vc_client despite it being listed in https://github.com/jacksonliam/mjpg-streamer/blob/master/mjpg-streamer-experimental/plugins/input_raspicam/CMakeLists.txt

I think this issue could be similar to https://github.com/raspberrypi/userland/issues/303

Do you know enough about cmake to try building with the linker flags `-Wl --no-as-needed`?

**Closed** 2018-10-21 19:05 UTC
