### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by goldjunge91** [jacksonliam/mjpg-streamer#255] opened 2020-06-10 13:04 UTC
```
(venv) beagle@beagle:~/mjpg-streamer/mjpg-streamer-experimental$ make
[ -d _build ] || mkdir _build
[ -f _build/Makefile ] || (cd _build && cmake  -DCMAKE_BUILD_TYPE=Release ..)
make -C _build
make[1]: Entering directory '/home/beagle/mjpg-streamer/mjpg-streamer-experimental/_build'
make[2]: Entering directory '/home/beagle/mjpg-streamer/mjpg-streamer-experimental/_build'
make[3]: Entering directory '/home/beagle/mjpg-streamer/mjpg-streamer-experimental/_build'
make[3]: Leaving directory '/home/beagle/mjpg-streamer/mjpg-streamer-experimental/_build'
[ 11%] Built target mjpg_streamer
make[3]: Entering directory '/home/beagle/mjpg-streamer/mjpg-streamer-experimental/_build'
make[3]: Leaving directory '/home/beagle/mjpg-streamer/mjpg-streamer-experimental/_build'
[ 18%] Built target input_file
make[3]: Entering directory '/home/beagle/mjpg-streamer/mjpg-streamer-experimental/_build'
make[3]: Leaving directory '/home/beagle/mjpg-streamer/mjpg-streamer-experimental/_build'
[ 33%] Built target input_http
make[3]: Entering directory '/home/beagle/mjpg-streamer/mjpg-streamer-experimental/_build'
make[3]: Leaving directory '/home/beagle/mjpg-streamer/mjpg-streamer-experimental/_build'
make[3]: Entering directory '/home/beagle/mjpg-streamer/mjpg-streamer-experimental/_build'
[ 37%] Building CXX object plugins/input_opencv/CMakeFiles/input_opencv.dir/input_opencv.cpp.o
/home/beagle/mjpg-streamer/mjpg-streamer-experimental/plugins/input_opencv/input_opencv.cpp:86:5: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
     " Help for input plugin..: "INPUT_PLUGIN_NAME"\n" \
     ^
/home/beagle/mjpg-streamer/mjpg-streamer-experimental/plugins/input_opencv/input_opencv.cpp: In function ‘void* worker_thread(void*)’:
/home/beagle/mjpg-streamer/mjpg-streamer-experimental/plugins/input_opencv/input_opencv.cpp:408:34: error: ‘CV_IMWRITE_JPEG_QUALITY’ was not declared in this scope
     compression_params.push_back(CV_IMWRITE_JPEG_QUALITY);
                                  ^~~~~~~~~~~~~~~~~~~~~~~
/home/beagle/mjpg-streamer/mjpg-streamer-experimental/plugins/input_opencv/input_opencv.cpp:408:34: note: suggested alternative: ‘IN_CMD_JPEG_QUALITY’
     compression_params.push_back(CV_IMWRITE_JPEG_QUALITY);
                                  ^~~~~~~~~~~~~~~~~~~~~~~
                                  IN_CMD_JPEG_QUALITY
plugins/input_opencv/CMakeFiles/input_opencv.dir/build.make:62: recipe for target 'plugins/input_opencv/CMakeFiles/input_opencv.dir/input_opencv.cpp.o' failed
make[3]: *** [plugins/input_opencv/CMakeFiles/input_opencv.dir/input_opencv.cpp.o] Error 1
make[3]: Leaving directory '/home/beagle/mjpg-streamer/mjpg-streamer-experimental/_build'
CMakeFiles/Makefile2:237: recipe for target 'plugins/input_opencv/CMakeFiles/input_opencv.dir/all' failed
make[2]: *** [plugins/input_opencv/CMakeFiles/input_opencv.dir/all] Error 2
make[2]: Leaving directory '/home/beagle/mjpg-streamer/mjpg-streamer-experimental/_build'
Makefile:129: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/beagle/mjpg-streamer/mjpg-streamer-experimental/_build'
Makefile:17: recipe for target 'all' failed
make: *** [all] Error 2
(venv) beagle@beagle:~/mjpg-streamer/mjpg-streamer-experimental$

```

**Comment by ChaosEngine** [comment] 2020-06-17 18:19
What is you system, complier? do you have opencv installed?

**Comment by CaptianNemo** [comment] 2020-07-02 02:46
See issue 160. Last post has the solution.
#160

**Comment by jacksonliam** [comment] 2020-07-03 12:35
Closing as seems to be duplicate of #160 and we have had no more info.

**Closed by jacksonliam** 2020-07-03 12:35 UTC
